server:
  port: 8080

spring:
  application:
    name: archive
  
  datasource:
    # PostgreSQL 서비스로 연결 (같은 namespace)
    url: jdbc:postgresql://postgresql-service:5432/${POSTGRES_DB:archive-db}
    username: ${POSTGRES_USER:archive-user}
    password: ${POSTGRES_PASSWORD:archive-password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false  # 프로덕션에서는 false로 설정
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false  # 프로덕션에서는 false로 설정
  
  data:
    redis:
      host: redis-service
      port: 6379

jwt:
  common:
    key: YXJjaGl2ZV9qd3Rfc2VjcmV0X2tleV90aGlzX2lzX2FfbG9uZ19zZWNyZXRfa2V5X2Zvcl9qd3RfdG9rZW5fZ2VuZXJhdGlvbl9hbmRfdmFsaWRhdGlvbg==

kakao:
  oauth:
    client-id: 86286e8983c278a1d5fb9b937b09d8f1
    client-secret: eZHbznKwU6QObpeRgSp7CSAVWXjlleiw
    redirect-uri: http://localhost:8080/oauth/kakao
    authorization-uri: https://kauth.kakao.com/oauth/authorize
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
