server:
  port: 8080

spring:
  application:
    name: archive
  
  datasource:
    # PostgreSQL 서비스로 연결 (같은 namespace)
    url: jdbc:postgresql://postgresql-service:5432/${POSTGRES_DB:archive-db}
    username: ${POSTGRES_USER:archive-user}
    password: ${POSTGRES_PASSWORD:archive-password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false  # 프로덕션에서는 false로 설정
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false  # 프로덕션에서는 false로 설정
  
  data:
    redis:
      host: redis-service
      port: 6379

jwt:
  common:
    key: YXJjaGl2ZV9qd3Rfc2VjcmV0X2tleV90aGlzX2lzX2FfbG9uZ19zZWNyZXRfa2V5X2Zvcl9qd3RfdG9rZW5fZ2VuZXJhdGlvbl9hbmRfdmFsaWRhdGlvbg==

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

slack:
  webhook:
    url: https://hooks.slack.com/services/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
