apiVersion: apps/v1
kind: Deployment
metadata:
  name: archive-api
  namespace: archive
  labels:
    app: archive-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: archive-api
  template:
    metadata:
      labels:
        app: archive-api
    spec:
      imagePullSecrets:
      - name: ncp-registry-secret
      containers:
      - name: archive-api
        image: archive-cr.kr.ncr.ntruss.com/archive-api:v-19
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "k8s"
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: postgresql-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: postgresql-config
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: POSTGRES_PASSWORD
        # NCP Object Storage 설정
        - name: NCP_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: ncp-object-storage-secret
              key: NCP_ACCESS_KEY
        - name: NCP_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: ncp-object-storage-secret
              key: NCP_SECRET_KEY
        - name: NCP_BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: ncp-object-storage-config
              key: NCP_BUCKET_NAME
        - name: SLACK_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: slack-secret
              key: SLACK_BOT_TOKEN
        - name: SLACK_CHANNEL
          valueFrom:
            secretKeyRef:
              name: slack-secret
              key: SLACK_CHANNEL
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
