apiVersion: v1
kind: Secret
metadata:
  name: ncp-object-storage-secret
  namespace: archive
type: Opaque
data:
  # ⚠️ 실제 배포 시 반드시 수정 필요 ⚠️
  # Base64로 인코딩된 값들
  # echo -n "your-actual-access-key" | base64
  NCP_ACCESS_KEY: bmNwX2lhbV9CUEFTS1I0dXFtUFhYTEFJNURodQ==
  # echo -n "your-actual-secret-key" | base64  
  NCP_SECRET_KEY: bmNwX2lhbV9CUEtTS1JGM3FKWVZxUEE0T2hOeG5rOGROdjBYSFBETjVN
