apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  namespace: archive
  labels:
    app: postgresql
spec:
  type: ClusterIP
  ports:
  - name: postgresql
    port: 5432
    targetPort: 5432
  selector:
    app: postgresql
