apiVersion: v1
kind: Service
metadata:
  name: archive-api-service
  namespace: archive
  labels:
    app: archive-api
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: archive-api
